package cpu

import (
	"github.com/smarkuck/nes/nes"
	"github.com/smarkuck/nes/nes/cpu/instruction"
	"github.com/smarkuck/nes/nes/cpu/instruction/cmd"
)

func NewCPU6502(b nes.Bus) CPU {
	return NewCPU(b, getCPU6502InstructionSet())
}

func getCPU6502InstructionSet() Instructions {
	return Instructions{
		0x00: instruction.NewImplied(cmd.BRK, 7),
		0x01: instruction.NewIndirectX(cmd.ORA, 6),
		0x05: instruction.NewZeroPage(cmd.ORA, 3),
		0x06: instruction.NewZeroPage(cmd.ASL, 5),
		0x08: instruction.NewImplied(cmd.PHP, 3),
		0x09: instruction.NewImmediate(cmd.ORA, 2),
		0x0a: instruction.NewAccumulative(cmd.AccumASL, 2),
		0x0d: instruction.NewAbsolute(cmd.ORA, 4),
		0x0e: instruction.NewAbsolute(cmd.ASL, 6),

		0x10: instruction.NewRelative(cmd.BPL),
		0x11: instruction.NewIndirectY(cmd.ORA, 5, 1),
		0x15: instruction.NewZeroPageX(cmd.ORA, 4),
		0x16: instruction.NewZeroPageX(cmd.ASL, 6),
		0x18: instruction.NewImplied(cmd.CLC, 2),
		0x19: instruction.NewAbsoluteY(cmd.ORA, 4, 1),
		0x1d: instruction.NewAbsoluteX(cmd.ORA, 4, 1),
		0x1e: instruction.NewAbsoluteX(cmd.ASL, 7, 0),

		0x20: instruction.NewAbsolute(cmd.JSR, 6),
		0x21: instruction.NewIndirectX(cmd.AND, 6),
		0x24: instruction.NewZeroPage(cmd.BIT, 3),
		0x25: instruction.NewZeroPage(cmd.AND, 3),
		0x26: instruction.NewZeroPage(cmd.ROL, 5),
		0x28: instruction.NewImplied(cmd.PLP, 4),
		0x29: instruction.NewImmediate(cmd.AND, 2),
		0x2a: instruction.NewAccumulative(cmd.AccumROL, 2),
		0x2c: instruction.NewAbsolute(cmd.BIT, 4),
		0x2d: instruction.NewAbsolute(cmd.AND, 4),
		0x2e: instruction.NewAbsolute(cmd.ROL, 6),

		0x30: instruction.NewRelative(cmd.BMI),
		0x31: instruction.NewIndirectY(cmd.AND, 5, 1),
		0x35: instruction.NewZeroPageX(cmd.AND, 4),
		0x36: instruction.NewZeroPageX(cmd.ROL, 6),
		0x38: instruction.NewImplied(cmd.SEC, 2),
		0x39: instruction.NewAbsoluteY(cmd.AND, 4, 1),
		0x3d: instruction.NewAbsoluteX(cmd.AND, 4, 1),
		0x3e: instruction.NewAbsoluteX(cmd.ROL, 7, 0),

		0x40: instruction.NewImplied(cmd.RTI, 6),
		0x41: instruction.NewIndirectX(cmd.EOR, 6),
		0x45: instruction.NewZeroPage(cmd.EOR, 3),
		0x46: instruction.NewZeroPage(cmd.LSR, 5),
		0x48: instruction.NewImplied(cmd.PHA, 3),
		0x49: instruction.NewImmediate(cmd.EOR, 2),
		0x4a: instruction.NewAccumulative(cmd.AccumLSR, 2),
		0x4c: instruction.NewAbsolute(cmd.JMP, 3),
		0x4d: instruction.NewAbsolute(cmd.EOR, 4),
		0x4e: instruction.NewAbsolute(cmd.LSR, 6),

		0x50: instruction.NewRelative(cmd.BVC),
		0x51: instruction.NewIndirectY(cmd.EOR, 5, 1),
		0x55: instruction.NewZeroPageX(cmd.EOR, 4),
		0x56: instruction.NewZeroPageX(cmd.LSR, 6),
		0x58: instruction.NewImplied(cmd.CLI, 2),
		0x59: instruction.NewAbsoluteY(cmd.EOR, 4, 1),
		0x5d: instruction.NewAbsoluteX(cmd.EOR, 4, 1),
		0x5e: instruction.NewAbsoluteX(cmd.LSR, 7, 0),

		0x60: instruction.NewImplied(cmd.RTS, 6),
		0x61: instruction.NewIndirectX(cmd.ADC, 6),
		0x65: instruction.NewZeroPage(cmd.ADC, 3),
		0x66: instruction.NewZeroPage(cmd.ROR, 5),
		0x68: instruction.NewImplied(cmd.PLA, 4),
		0x69: instruction.NewImmediate(cmd.ADC, 2),
		0x6a: instruction.NewAccumulative(cmd.AccumROR, 2),
		0x6c: instruction.NewIndirect(cmd.JMP, 5),
		0x6d: instruction.NewAbsolute(cmd.ADC, 4),
		0x6e: instruction.NewAbsolute(cmd.ROR, 6),

		0x70: instruction.NewRelative(cmd.BVS),
		0x71: instruction.NewIndirectY(cmd.ADC, 5, 1),
		0x75: instruction.NewZeroPageX(cmd.ADC, 4),
		0x76: instruction.NewZeroPageX(cmd.ROR, 6),
		0x78: instruction.NewImplied(cmd.SEI, 2),
		0x79: instruction.NewAbsoluteY(cmd.ADC, 4, 1),
		0x7d: instruction.NewAbsoluteX(cmd.ADC, 4, 1),
		0x7e: instruction.NewAbsoluteX(cmd.ROR, 7, 0),

		0x81: instruction.NewIndirectX(cmd.STA, 6),
		0x84: instruction.NewZeroPage(cmd.STY, 3),
		0x85: instruction.NewZeroPage(cmd.STA, 3),
		0x86: instruction.NewZeroPage(cmd.STX, 3),
		0x88: instruction.NewImplied(cmd.DEY, 2),
		0x8a: instruction.NewImplied(cmd.TXA, 2),
		0x8c: instruction.NewAbsolute(cmd.STY, 4),
		0x8d: instruction.NewAbsolute(cmd.STA, 4),
		0x8e: instruction.NewAbsolute(cmd.STX, 4),

		0x90: instruction.NewRelative(cmd.BCC),
		0x91: instruction.NewIndirectY(cmd.STA, 6, 0),
		0x94: instruction.NewZeroPageX(cmd.STY, 4),
		0x95: instruction.NewZeroPageX(cmd.STA, 4),
		0x96: instruction.NewZeroPageY(cmd.STX, 4),
		0x98: instruction.NewImplied(cmd.TYA, 2),
		0x99: instruction.NewAbsoluteY(cmd.STA, 5, 0),
		0x9a: instruction.NewImplied(cmd.TXS, 2),
		0x9d: instruction.NewAbsoluteX(cmd.STA, 5, 0),

		0xa0: instruction.NewImmediate(cmd.LDY, 2),
		0xa1: instruction.NewIndirectX(cmd.LDA, 6),
		0xa2: instruction.NewImmediate(cmd.LDX, 2),
		0xa4: instruction.NewZeroPage(cmd.LDY, 3),
		0xa5: instruction.NewZeroPage(cmd.LDA, 3),
		0xa6: instruction.NewZeroPage(cmd.LDX, 3),
		0xa8: instruction.NewImplied(cmd.TAY, 2),
		0xa9: instruction.NewImmediate(cmd.LDA, 2),
		0xaa: instruction.NewImplied(cmd.TAX, 2),
		0xac: instruction.NewAbsolute(cmd.LDY, 4),
		0xad: instruction.NewAbsolute(cmd.LDA, 4),
		0xae: instruction.NewAbsolute(cmd.LDX, 4),

		0xb0: instruction.NewRelative(cmd.BCS),
		0xb1: instruction.NewIndirectY(cmd.LDA, 5, 1),
		0xb4: instruction.NewZeroPageX(cmd.LDY, 4),
		0xb5: instruction.NewZeroPageX(cmd.LDA, 4),
		0xb6: instruction.NewZeroPageY(cmd.LDX, 4),
		0xb8: instruction.NewImplied(cmd.CLV, 2),
		0xb9: instruction.NewAbsoluteY(cmd.LDA, 4, 1),
		0xba: instruction.NewImplied(cmd.TSX, 2),
		0xbc: instruction.NewAbsoluteX(cmd.LDY, 4, 1),
		0xbd: instruction.NewAbsoluteX(cmd.LDA, 4, 1),
		0xbe: instruction.NewAbsoluteY(cmd.LDX, 4, 1),

		0xc0: instruction.NewImmediate(cmd.CPY, 2),
		0xc1: instruction.NewIndirectX(cmd.CMP, 6),
		0xc4: instruction.NewZeroPage(cmd.CPY, 3),
		0xc5: instruction.NewZeroPage(cmd.CMP, 3),
		0xc6: instruction.NewZeroPage(cmd.DEC, 5),
		0xc8: instruction.NewImplied(cmd.INY, 2),
		0xc9: instruction.NewImmediate(cmd.CMP, 2),
		0xca: instruction.NewImplied(cmd.DEX, 2),
		0xcc: instruction.NewAbsolute(cmd.CPY, 4),
		0xcd: instruction.NewAbsolute(cmd.CMP, 4),
		0xce: instruction.NewAbsolute(cmd.DEC, 6),

		0xd0: instruction.NewRelative(cmd.BNE),
		0xd1: instruction.NewIndirectY(cmd.CMP, 5, 1),
		0xd5: instruction.NewZeroPageX(cmd.CMP, 4),
		0xd6: instruction.NewZeroPageX(cmd.DEC, 6),
		0xd8: instruction.NewImplied(cmd.CLD, 2),
		0xd9: instruction.NewAbsoluteY(cmd.CMP, 4, 1),
		0xdd: instruction.NewAbsoluteX(cmd.CMP, 4, 1),
		0xde: instruction.NewAbsoluteX(cmd.DEC, 7, 0),

		0xe0: instruction.NewImmediate(cmd.CPX, 2),
		0xe1: instruction.NewIndirectX(cmd.SBC, 6),
		0xe4: instruction.NewZeroPage(cmd.CPX, 3),
		0xe5: instruction.NewZeroPage(cmd.SBC, 3),
		0xe6: instruction.NewZeroPage(cmd.INC, 5),
		0xe8: instruction.NewImplied(cmd.INX, 2),
		0xe9: instruction.NewImmediate(cmd.SBC, 2),
		0xea: instruction.NewImplied(cmd.NOP, 2),
		0xec: instruction.NewAbsolute(cmd.CPX, 4),
		0xed: instruction.NewAbsolute(cmd.SBC, 4),
		0xee: instruction.NewAbsolute(cmd.INC, 6),

		0xf0: instruction.NewRelative(cmd.BEQ),
		0xf1: instruction.NewIndirectY(cmd.SBC, 5, 1),
		0xf5: instruction.NewZeroPageX(cmd.SBC, 4),
		0xf6: instruction.NewZeroPageX(cmd.INC, 6),
		0xf8: instruction.NewImplied(cmd.SED, 2),
		0xf9: instruction.NewAbsoluteY(cmd.SBC, 4, 1),
		0xfd: instruction.NewAbsoluteX(cmd.SBC, 4, 1),
		0xfe: instruction.NewAbsoluteX(cmd.INC, 7, 0),
	}
}
